In [3]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

In [136]:
#questions = pd.read_csv('/Users/kevin/Questions.csv')
answers = pd.read_csv('/Users/kevin/fletcher/data/Answers.csv')
#tags = pd.read_csv('/Users/kevin/Tags.csv')

In [137]:
answers.shape

(987122, 6)

In [138]:
answers = answers[answers.Score >= 5]
answers.dropna(inplace=True)
answers.head()


Id  OwnerUserId          CreationDate  ParentId  Score  \
2  536        161.0  2008-08-02T18:49:07Z       502      9   
3  538        156.0  2008-08-02T18:56:56Z       535     23   
4  541        157.0  2008-08-02T19:06:40Z       535     20   
5  595        116.0  2008-08-03T01:17:36Z       594     25   
6  660        197.0  2008-08-03T12:09:18Z       535     14   

                                                Body  
2  <p>You can use ImageMagick's convert utility f...  
3  <p>One possibility is Hudson.  It's written in...  
4  <p>We run <a href="http://buildbot.net/trac">B...  
5  <p>The canonical way is to use the built-in cu...  
6  <p>Second the Buildbot - Trac integration. You...

In [6]:
a = answers[:100].groupby('OwnerUserId').sum()

In [7]:
b = answers[:100].groupby('OwnerUserId').agg(lambda x: ' '.join(x))


In [9]:
pd.concat([a.Score,b.Body], axis=1).head()

Score                                               Body
OwnerUserId                                                          
13.0            25  <p>ImageMagick delegates the PDF->bitmap conve...
25.0             5  <p><a href="http://en.wikipedia.org/wiki/Qt_%2...
30.0           118  <pre class="lang-py prettyprint-override"><cod...
77.0             8  <P>If you are looking for user facing interact...
92.0            17  <p>MySQLdb is what I have used before.</p>\r\n...

In [10]:
answers[answers.Id == 34643081].Body.values

array([ '<p>The pooling and convolutional ops slide a "window" across the input tensor.  Using <a href="https://www.tensorflow.org/versions/master/api_docs/python/nn.html#conv2d"><code>tf.nn.conv2d</code></a> as an example: If the input tensor has 4 dimensions:  <code>[batch, height, width, channels]</code>, then the convolution operates on a 2D window on the <code>height, width</code> dimensions.</p>\n\n<p><code>strides</code> determines how much the window shifts by in each of the dimensions.  The typical use sets the first (the batch) and last (the depth) stride to 1.</p>\n\n<p>Let\'s use a very concrete example:  Running a 2-d convolution over a 32x32 greyscale input image.  I say greyscale because then the input image has depth=1, which helps keep it simple.  Let that image look like this:</p>\n\n<pre><code>00 01 02 03 04 ...\n10 11 12 13 14 ...\n20 21 22 23 24 ...\n30 31 32 33 34 ...\n...\n</code></pre>\n\n<p>Let\'s run a 2x2 convolution window over a single example (batch size =

In [11]:
answers.shape

(121045, 6)

In [195]:
sum([[x,y] for x,y in zip(range(7), range(1,8))],[])

[0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7]

In [12]:
tfidf = TfidfVectorizer(stop_words='english', token_pattern="\\b[a-zA-Z][a-zA-Z]+\\b", min_df=10)
answers_vecs = tfidf.fit_transform(answers.Body.values)

In [13]:
cv = CountVectorizer(stop_words='english', token_pattern="\\b[a-zA-Z][a-zA-Z]+\\b", min_df=10)
answers_vecs = cv.fit_transform(answers.Body.values)

In [163]:
a = cv.transform(["flask webapp"])

In [119]:
# import pickle

# with open('/Users/kevin/fletcher/data/input.pkl', 'wb') as picklefile:
#     pickle.dump(cv, picklefile)
    
# with open('/Users/kevin/fletcher/data/answers.pkl', 'wb') as picklefile:
#     pickle.dump(answers, picklefile)
    
# with open('/Users/kevin/fletcher/data/answers_vecs.pkl', 'wb') as picklefile:
#     pickle.dump(answers_vecs, picklefile)

    

In [228]:
answer = [0,0,0,0,0]
keywords_vec = cv.transform(["Keras"])

In [229]:
user = [0,0,0,0,0]
url = []
username = []

In [234]:
username

['mattdns', 'Ben Kamphaus', 'Ty Pavicich', 'Victor Smt', 'ncfirth']

In [242]:
user_string

'Users <a href=http://stackoverflow.com/users/5407700>mattdns</a>, <a href=http://stackoverflow.com/users/3801886>Ben Kamphaus</a>, <a href=http://stackoverflow.com/users/2255993>Ty Pavicich</a>, <a href=http://stackoverflow.com/users/3867406>Victor Smt</a>,     and <a href=http://stackoverflow.com/users/5678534>ncfirth</a> can help you with your question'

In [239]:


for i in range(5):
    answer[i] = answers.iloc[cosine_similarity(keywords_vec, answers_vecs).argsort()[0][:-6:-1]].Body.values[i]
    user[i] = answers.iloc[cosine_similarity(keywords_vec, answers_vecs).argsort()[0][:-6:-1]].OwnerUserId.values.astype(int)[i]

    url.append('http://stackoverflow.com/users/' + str(user[i]))
    response = requests.get(url[i])
    page = response.text
    soup = BeautifulSoup(page, 'lxml')
    username.append(str(soup.find('title')).split('-')[0].strip()[12:])
    
user_string = "Users <a href={}>{}</a>, <a href={}>{}</a>, <a href={}>{}</a>, <a href={}>{}</a>, \
and <a href={}>{}</a> can help you with your question".format(*sum([[x,y] for x,y in zip(url, username)],[])) 


In [188]:
cv.get_feature_names()

[u'aa',
 u'aaa',
 u'aaaa',
 u'aaaaa',
 u'aab',
 u'aabbcc',
 u'aac',
 u'aapl',
 u'aardvark',
 u'aaron',
 u'aaronasterling',
 u'aaronsw',
 u'ab',
 u'aba',
 u'abandon',
 u'abandoned',
 u'abarnert',
 u'abb',
 u'abbreviate',
 u'abbreviated',
 u'abbreviation',
 u'abbreviations',
 u'abc',
 u'abcabc',
 u'abcd',
 u'abcde',
 u'abcdef',
 u'abcdefg',
 u'abcdefgh',
 u'abcdefghij',
 u'abcdefghijklmnopqrstuvwxyz',
 u'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz',
 u'abcmeta',
 u'abcs',
 u'abd',
 u'abi',
 u'abilities',
 u'ability',
 u'able',
 u'abnormal',
 u'abort',
 u'aborted',
 u'aborting',
 u'abracadabra',
 u'abrams',
 u'abruptly',
 u'abs',
 u'absence',
 u'absent',
 u'absolute',
 u'absolutely',
 u'abspath',
 u'abstract',
 u'abstractbaseuser',
 u'abstracted',
 u'abstracting',
 u'abstraction',
 u'abstractions',
 u'abstractmethod',
 u'abstracts',
 u'abstractuser',
 u'absurd',
 u'abuse',
 u'abused',
 u'abuses',
 u'abusing',
 u'ac',
 u'aca',
 u'academic',
 u'acb',
 u'acc',
 u'accel',
 u'accelera

In [126]:
answers_vecs.shape

(121045, 15140)

In [127]:
from sklearn.metrics.pairwise import cosine_similarity

In [176]:
dense_vecs = answers_vecs.todense()

In [178]:
dense_vecs.

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ..., 
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [128]:
sorted(cosine_similarity(a,answers_vecs)[0])[-5:]

[0.49656353316142077,
 0.49656353316142077,
 0.50350881497801336,
 0.50444918477586076,
 0.53215208419019144]

In [129]:
cosine_similarity(a,answers_vecs).argsort()[0][-5:]

array([ 30033,  67934, 111084,  95753,  49100])

In [130]:
top5_users = answers.iloc[cosine_similarity(a,answers_vecs).argsort()[0][:-5:-1]].OwnerUserId.values.astype(int)
top5_users

array([   4558, 3414157,   13009, 1819983])

In [131]:
top5_answers = answers.iloc[cosine_similarity(a,answers_vecs).argsort()[0][:-5:-1]].Id.values.astype(int)
top5_answers

array([ 8896780, 22525896, 31146549, 13462351])

In [170]:
answers.iloc[cosine_similarity(a,answers_vecs).argsort()[0][:-6:-1]].Body.values[4]

'<p>Flask has an <a href="http://packages.python.org/Flask-OAuth/">OpenAuth</a> <a href="http://flask.pocoo.org/extensions/">extension</a> that\'s written by the <a href="https://github.com/mitsuhiko/flask-oauth">Armin Ronacher</a> (Flask\'s author).  It provides Flask with support for Open Auth 1.0. </p>\n'

In [45]:
from bs4 import BeautifulSoup
import requests


In [142]:
url = 'http://stackoverflow.com/users/'


In [48]:
response = requests.get(url)

assert response.status_code == 200, "Website not responding correctly"

In [49]:
i = 0
url += str(top5_users[i])
url

'http://stackoverflow.com/users/4678222'

In [171]:
import requests 
url = 'http://stackoverflow.com/users/' + str(users[i])

response = requests.get(url)
page = response.text
soup = BeautifulSoup(page, 'lxml')
user = str(soup.find('title')).split('-')[0].strip()[12:]
print "User [{}]({}) can help you with your question".format(user, url)

User [](http://stackoverflow.com/users/) can help you with your question


In [52]:
print soup

<!DOCTYPE html>
<html>
<head>
<title>User Zhongyu Kuang - Stack Overflow</title>
<link href="//cdn.sstatic.net/Sites/stackoverflow/img/favicon.ico?v=4f32ecc8f43d" rel="shortcut icon"/>
<link href="//cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon.png?v=c78bd457575a" rel="apple-touch-icon image_src"/>
<link href="/opensearch.xml" rel="search" title="Stack Overflow" type="application/opensearchdescription+xml"/>
<meta content="summary" name="twitter:card"/>
<meta content="stackoverflow.com" name="twitter:domain"/>
<meta content="website" property="og:type"/>
<meta content="http://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded&amp;a" itemprop="image primaryImageOfPage" property="og:image"/>
<meta content="User Zhongyu Kuang" itemprop="title name" name="twitter:title" property="og:title"/>
<meta content="Q&amp;A for professional and enthusiast programmers" itemprop="description" name="twitter:description" property="og:description"/>
<meta content="ht

In [53]:
x =answers[:5]
x

Id  OwnerUserId          CreationDate  ParentId  Score  \
2  536        161.0  2008-08-02T18:49:07Z       502      9   
3  538        156.0  2008-08-02T18:56:56Z       535     23   
4  541        157.0  2008-08-02T19:06:40Z       535     20   
5  595        116.0  2008-08-03T01:17:36Z       594     25   
6  660        197.0  2008-08-03T12:09:18Z       535     14   

                                                Body  
2  <p>You can use ImageMagick's convert utility f...  
3  <p>One possibility is Hudson.  It's written in...  
4  <p>We run <a href="http://buildbot.net/trac">B...  
5  <p>The canonical way is to use the built-in cu...  
6  <p>Second the Buildbot - Trac integration. You...

In [54]:
x.set_value(2, 'Body', x.loc[2, 'Body'].replace(' ', '').split())

Id  OwnerUserId          CreationDate  ParentId  Score  \
2  536        161.0  2008-08-02T18:49:07Z       502      9   
3  538        156.0  2008-08-02T18:56:56Z       535     23   
4  541        157.0  2008-08-02T19:06:40Z       535     20   
5  595        116.0  2008-08-03T01:17:36Z       594     25   
6  660        197.0  2008-08-03T12:09:18Z       535     14   

                                                Body  
2  [<p>YoucanuseImageMagick'sconvertutilityforthi...  
3  <p>One possibility is Hudson.  It's written in...  
4  <p>We run <a href="http://buildbot.net/trac">B...  
5  <p>The canonical way is to use the built-in cu...  
6  <p>Second the Buildbot - Trac integration. You...

In [55]:
x.ix[2].Body[0]

'<p>YoucanuseImageMagick\'sconvertutilityforthis,seesomeexamplesin<ahref="https://web.archive.org/web/20120413111338/http://studio.imagemagick.org/pipermail/magick-users/2002-May/002636.html"rel="nofollow">http://studio.imagemagick.org/pipermail/magick-users/2002-May/002636.html</a>'